### ISSUE TITLE
Bug on signup for hosting

### ISSUE THREAD

**Issue by MeXaaR** [Meteor-Community-Packages/website#1]
HI guys, I've got a bug on your website. The form to signup for hosting stops working on submit.
`Uncaught ReferenceError: recurly is not defined`
So, for me, it is not possible to signup for hosting.
I am on Firefox, didn't test on Chromium though

**Comment by copleykj** [comment]
It seems like you may want to report a bug which exists on the `meteor.com` website. This repo is however for the `meteorjs.community` site. Your best bet is to email support@meteor.com and they should be able to address this issue.

**Comment by MeXaaR** [comment]
arh, alright, sorry :+1:
